#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Agent broker wizard: keeps Netlify / Vercel / Supabase / Apify tokens where agents cannot read them.
#   wizard.sh               first time on this Mac: vault, install the broker, add projects, log out global logins
#   wizard.sh add-project   later: add (or finish) projects only
# Run it in your own Terminal: it asks for your Mac password, and tokens are typed hidden straight into the broker
# (agent-broker-admin). Nothing is written to .env files. Guide: ../SKILL.md

ENV_FILE=/dev/null # no values are remembered in files; tokens live only in the broker and your vault
SKILL_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
BROKER_SRC="$SKILL_DIR/broker"
VAULT_DIR="$HOME/Secrets"
MODE=${1:-setup}
DONE=()
dir="" move="" conn="" P_PATH="" P_NAME="" P_REF="" site="" org="" vproj="" # filled by ask/ask_default (printf -v)

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# ask_default VAR "Prompt" default — visible input; Enter keeps the default.
ask_default() {
  local input
  if [[ -n "$3" ]]; then printf '  %s%s%s %s[%s]%s ' "$BOLD" "$2" "$RESET" "$DIM" "$3" "$RESET"; else printf '  %s%s%s ' "$BOLD" "$2" "$RESET"; fi
  read -r input || true
  printf -v "$1" '%s' "${input:-$3}"
}

# confirm_yes "question" — Y/n gate; returns success unless the answer starts with n.
confirm_yes() {
  local reply=""
  printf '  %s? %s [Y/n] ' "$YELLOW" "$1"
  read -r reply || true
  [[ ! "$reply" =~ ^[Nn] ]]
}

# json_field FILE FIELD — a top-level field of a JSON file, or nothing.
json_field() {
  node -e 'try { const v = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"))[process.argv[2]]; if (v) console.log(v) } catch {}' "$1" "$2" 2>/dev/null || true
}

# stored_keys PROJECT — names of the keys the broker holds for a project (never values).
stored_keys() {
  agent-broker projects 2>/dev/null | node -e 'let s = ""; process.stdin.on("data", (d) => (s += d)).on("end", () => {
    const p = JSON.parse(s || "[]").find((x) => x.project === process.argv[1]); console.log((p?.keys ?? []).join(" ")) })' "$1" 2>/dev/null || true
}
has_key() { [[ " $(stored_keys "$1") " == *" $2 "* ]]; }

# secret_looking_keys FILE — keys whose name or value looks like a secret (names only are printed).
secret_looking_keys() {
  awk '/^[A-Za-z_][A-Za-z0-9_]*=/ {
    i = index($0, "="); k = substr($0, 1, i - 1); v = substr($0, i + 1)
    if (k ~ /(ANON|PUBLISHABLE|PUBLIC)/) next
    if (k ~ /(TOKEN|SECRET|PASSWORD|PASSWD|SERVICE_ROLE|PRIVATE|API_KEY|ACCESS_KEY)/ || v ~ /:\/\/[^\/:@]+:[^@]+@/) printf "%s ", k
  }' "$1"
}

# admin ARGS... — agent-broker-admin; on failure (wrong password, bad value) offer one retry.
admin() {
  agent-broker-admin "$@" && return 0
  warn "That did not work (see the message above)."
  if confirm "Try again?"; then agent-broker-admin "$@" && return 0; fi
  SKIPPED+=("agent-broker-admin $1 ${2:-}")
  return 1
}

# save_token PROJECT KEY URL "how to get it" — open the token page, then store the token hidden in the broker.
save_token() {
  local project="$1" key="$2" url="$3" how="$4"
  if has_key "$project" "$key"; then note "$key is already stored for $project (skip)."; return; fi
  printf '\n  %s%s%s\n' "$BOLD" "$key" "$RESET"
  open_url "$url"
  step "$how"
  step "Save the token in KeePassXC first (entry name: $project $key)."
  pause "Press Enter when it is in KeePassXC and in your clipboard"
  say "Paste it at the hidden prompt below; then type your Mac password."
  admin set "$project" "$key" && DONE+=("$project: $key stored")
}

# read_only_db_user PROJECT REF — create a read-only Supabase user and store its connection URL as SUPABASE_READ_URL.
read_only_db_user() {
  local project="$1" ref="$2" pw conn url
  pw=$(openssl rand -hex 24)
  pbcopy <<SQL
-- agent_reader: read-only database user for agent queries (agent-broker supabase query).
do \$\$ begin
  if not exists (select 1 from pg_roles where rolname = 'agent_reader') then create role agent_reader login; end if;
end \$\$;
alter role agent_reader with login password '$pw' bypassrls noinherit;
alter role agent_reader set default_transaction_read_only = on;
alter role agent_reader set statement_timeout = '120s';
grant usage on schema public to agent_reader;
grant select on all tables in schema public to agent_reader;
alter default privileges in schema public grant select on tables to agent_reader;
SQL
  open_url "https://supabase.com/dashboard/project/$ref/sql/new"
  step "The SQL is in your clipboard. Paste it into the SQL editor and click Run."
  note "It creates agent_reader: it can read every table in schema public and cannot change anything."
  pause "Press Enter when it ran without an error"
  printf '' | pbcopy
  open_url "https://supabase.com/dashboard/project/$ref"
  step "Click Connect (top of the page), choose Session pooler, and copy the connection string."
  note "It looks like postgresql://postgres.$ref:[YOUR-PASSWORD]@aws-....pooler.supabase.com:5432/postgres"
  ask conn "Paste the connection string:"
  url=${conn/postgres.$ref:/agent_reader.$ref:}
  url=${url/\[YOUR-PASSWORD\]/$pw}
  if [[ "$url" == "$conn" || "$url" != *"agent_reader.$ref:$pw@"* ]]; then
    warn "That does not look like the Session pooler string for project $ref; skipped."
    SKIPPED+=("$project: read-only database user (re-run: wizard.sh add-project)")
    return
  fi
  say "Storing it in the broker (type your Mac password)."
  printf '%s\n' "$url" | admin set "$project" SUPABASE_READ_URL && DONE+=("$project: SUPABASE_READ_URL stored (user agent_reader)")
  if confirm "Show the URL once so you can save it in KeePassXC?"; then say "$url"; pause "Press Enter when it is saved"; fi
}

# ── Before the stages ────────────────────────────────────────────────────
case "$MODE" in setup|add-project) ;; *) die "usage: wizard.sh [setup|add-project]" ;; esac
[[ -t 0 && -t 1 ]] || die "Run this in your own Terminal app, not through an agent."
[[ "$(uname)" == Darwin ]] || die "This wizard is for macOS."
command -v node >/dev/null || die "Node is missing (the broker copies your Node). Install it first."
[[ "$MODE" == setup ]] && { command -v brew >/dev/null || die "Homebrew is missing (needed for KeePassXC)."; }
[[ "$MODE" == add-project ]] && { command -v agent-broker >/dev/null || die "The broker is not installed yet: run wizard.sh (setup) first."; }

printf '\n  How many projects do you want to add in this run? (a project = one code folder) [1] '
read -r PROJECT_COUNT || true
PROJECT_COUNT=${PROJECT_COUNT:-1}
[[ "$PROJECT_COUNT" =~ ^[0-9]$ ]] || die "Give a number from 0 to 9."

if [[ "$MODE" == setup ]]; then
  TOTAL_STAGES=$((5 + 4 * PROJECT_COUNT))
  TOTAL_MINUTES=$((13 + 11 * PROJECT_COUNT))
else
  TOTAL_STAGES=$((2 + 4 * PROJECT_COUNT))
  TOTAL_MINUTES=$((2 + 11 * PROJECT_COUNT))
fi

banner "Agent broker — tokens that agents cannot read"

stage "What happens" 1
say "Agents use your Netlify, Vercel, Supabase and Apify accounts only through the broker."
say "The broker keeps the tokens under a separate macOS user (_deployer). Agents cannot read them."
if [[ "$MODE" == setup ]]; then
  step "1. Make a KeePassXC vault: your own copy of every token."
  step "2. Install the broker (needs your Mac password)."
fi
step "Add $PROJECT_COUNT project(s): folder, services, secrets in .env files, account tokens, instructions for its agents."
[[ "$MODE" == setup ]] && step "Then log out the global logins, so no command falls back to a random account."
note "Each step that changes the broker asks for your Mac password. That is on purpose."
pause

if [[ "$MODE" == setup ]]; then
  stage "Your vault (KeePassXC)" 5
  say "KeePassXC keeps your own copy of every token. Agents never use it."
  if [[ ! -d /Applications/KeePassXC.app ]]; then
    if confirm_yes "Install KeePassXC with Homebrew now?"; then brew install --cask keepassxc; else SKIPPED+=("install KeePassXC"); fi
  fi
  mkdir -p "$VAULT_DIR" && chmod 700 "$VAULT_DIR"
  open -a KeePassXC 2>/dev/null || true
  if compgen -G "$VAULT_DIR/*.kdbx" >/dev/null; then
    step "Unlock your vault in KeePassXC ($(basename "$(compgen -G "$VAULT_DIR/*.kdbx" | head -1)"))."
  else
    step "In KeePassXC click 'Create new database' (or menu Database → New Database)."
    step "Choose a strong master password that you will not forget."
    step "Save the file as $VAULT_DIR/tokens.kdbx"
  fi
  note "Back up the vault later (Syncthing). Without the master password the file is useless to anyone."
  pause "Press Enter when the vault is open"

  stage "Install the broker" 5
  say "This creates the hidden user _deployer, copies the broker and its own CLIs to /opt/agent-broker,"
  say "adds the commands agent-broker and agent-broker-admin, and a sudo rule. It downloads about 300 MB."
  command -v agent-broker >/dev/null && note "Already installed: this updates it."
  (cd "$BROKER_SRC" && node --test test/*.test.mjs >/dev/null 2>&1) || die "The broker's own tests fail: ask your agent to fix them first."
  if confirm_yes "Install (or update) now? It asks for your Mac password."; then
    (cd "$BROKER_SRC" && sudo ./install.sh) || die "The install failed (see above). Fix it, then run the wizard again."
    agent-broker help >/dev/null || die "agent-broker does not run after the install."
    DONE+=("broker installed in /opt/agent-broker")
  else
    die "The next steps need the broker. Run the wizard again when you are ready."
  fi
fi

for ((i = 1; i <= PROJECT_COUNT; i++)); do
  # ── Project: folder and services ──
  stage "Project $i of $PROJECT_COUNT — folder and services" 2
  say "A project is one code folder. Each service in it uses one account."
  while :; do
    ask P_PATH "Project folder (full path):"
    P_PATH=${P_PATH/#\~/$HOME}
    P_PATH=${P_PATH%/}
    [[ -d "$P_PATH" ]] && break
    warn "No such folder: $P_PATH"
  done
  default_name=$(basename "$P_PATH" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9_\n-' '-')
  while :; do
    ask_default P_NAME "Project name for the broker:" "$default_name"
    [[ "$P_NAME" =~ ^[a-z0-9][a-z0-9_-]{0,62}$ ]] && break
    warn "Use lowercase letters, digits, - and _ only."
  done
  args=(project "$P_NAME" --path "$P_PATH")
  P_SERVICES=()
  P_REF=""

  site=$(json_field "$P_PATH/.netlify/state.json" siteId)
  if { [[ -n "$site" ]] && confirm_yes "Netlify: found site $site. Use it?"; } || { [[ -z "$site" ]] && confirm "Does this project deploy to Netlify?"; }; then
    if [[ -z "$site" ]]; then
      open_url "https://app.netlify.com"
      step "Open the project → Project configuration → General → Project details, and copy the Project ID."
      ask site "Paste the Netlify Project ID:"
    fi
    ask_default dir "Folder with the built files, inside the project (e.g. dist, web/dist):" "dist"
    args+=(--netlify-site "$site" --netlify-dir "$dir")
    P_SERVICES+=(netlify)
  fi

  org=$(json_field "$P_PATH/.vercel/project.json" orgId)
  vproj=$(json_field "$P_PATH/.vercel/project.json" projectId)
  if { [[ -n "$vproj" ]] && confirm_yes "Vercel: found project $vproj. Use it?"; } || { [[ -z "$vproj" ]] && confirm "Does this project deploy to Vercel?"; }; then
    if [[ -z "$vproj" ]]; then
      open_url "https://vercel.com/dashboard"
      step "Open the project → Settings → General, and copy the Project ID."
      ask vproj "Paste the Vercel Project ID:"
      step "Open the team (or personal account) → Settings → General, and copy the Team ID (starts with team_)."
      ask org "Paste the Team ID:"
      note "If a label differs on the page, look for the ID fields in those Settings pages."
    fi
    args+=(--vercel-org "$org" --vercel-project "$vproj")
    P_SERVICES+=(vercel)
  fi

  if confirm "Does this project use a Supabase project?"; then
    open_url "https://supabase.com/dashboard/projects"
    step "Open the Supabase project. Its ref is the part after /project/ in the address bar."
    ask P_REF "Paste the project ref:"
    args+=(--supabase-ref "$P_REF")
    P_SERVICES+=(supabase)
  fi

  actors=$(find "$P_PATH" -maxdepth 3 -path '*/.actor/actor.json' -not -path '*/node_modules/*' 2>/dev/null | wc -l | tr -d ' ')
  if { [[ "$actors" != 0 ]] && confirm_yes "Apify: found $actors actor folder(s). Use Apify?"; } || { [[ "$actors" == 0 ]] && confirm "Does this project push or run Apify actors?"; }; then
    args+=(--apify)
    P_SERVICES+=(apify)
  fi

  say "Saving the project in the broker (type your Mac password)."
  services="${P_SERVICES[*]+${P_SERVICES[*]}}"
  admin "${args[@]}" && DONE+=("project $P_NAME (${services:-no services})")
  pause

  # ── Project: secrets already in .env files ──
  stage "Project $P_NAME — secrets already in .env files" 3
  env_files=()
  while IFS= read -r f; do env_files+=("$f"); done < <(find "$P_PATH" -maxdepth 1 -type f -name '.env*' ! -name '*.example' ! -name '*.sample' ! -name '*.template' 2>/dev/null | sort)
  if (( ${#env_files[@]} == 0 )); then
    say "No .env files in $P_PATH. Nothing to move."
    pause
  fi
  for f in ${env_files[@]+"${env_files[@]}"}; do
    printf '\n  %s%s%s\n' "$BOLD" "$f" "$RESET"
    note "Keys: $(grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$f" | tr -d '=' | tr '\n' ' ')"
    suggested=$(secret_looking_keys "$f")
    say "Agents can read these files. Move the secrets into the broker; keep public values (URLs, anon keys, ids)."
    ask_default move "Keys to move (space-separated; '-' = none):" "${suggested% }"
    [[ -z "$move" || "$move" == "-" ]] && continue
    if confirm_yes "Show their values here so you can copy them into KeePassXC?"; then
      for k in $move; do grep -m1 "^$k=" "$f" | sed 's/^/    /' || warn "$k is not in $f"; done
    fi
    step "Save each value in KeePassXC (entry name: $P_NAME <KEY>)."
    pause "Press Enter when all of them are in KeePassXC"
    _clear
    warn "Code that reads these keys from $f stops working on this Mac (run it on GitHub Actions instead)."
    if confirm_yes "Move $move into the broker now? They are deleted from $(basename "$f")."; then
      # shellcheck disable=SC2086 # one argument per key
      admin import "$P_NAME" "$f" $move && DONE+=("$P_NAME: moved $move out of $(basename "$f")")
    fi
  done

  # ── Project: account tokens ──
  stage "Project $P_NAME — account tokens" 5
  if (( ${#P_SERVICES[@]} == 0 )); then say "No services for this project, so no account tokens."; pause; fi
  for svc in ${P_SERVICES[@]+"${P_SERVICES[@]}"}; do
    case "$svc" in
      netlify) save_token "$P_NAME" NETLIFY_AUTH_TOKEN "https://app.netlify.com/user/applications#personal-access-tokens" \
        "Log in to the Netlify account that owns this project. Personal access tokens → New access token; name it agent-broker $P_NAME; pick an expiry if offered." ;;
      vercel) save_token "$P_NAME" VERCEL_TOKEN "https://vercel.com/account/settings/tokens" \
        "Create a token; Scope = the team that owns this project; pick an expiry." ;;
      apify) save_token "$P_NAME" APIFY_TOKEN "https://console.apify.com/settings/integrations" \
        "Log in to the Apify account that owns the actors, and copy its API token (or create a new one)." ;;
      supabase)
        save_token "$P_NAME" SUPABASE_ACCESS_TOKEN "https://supabase.com/dashboard/account/tokens" \
          "Generate new token; name it agent-broker $P_NAME; if you can limit it to one project, choose this one."
        if has_key "$P_NAME" SUPABASE_READ_URL; then
          note "SUPABASE_READ_URL is already stored for $P_NAME (skip)."
        elif confirm_yes "Create a read-only database user, so agents can run read-only SQL (agent-broker supabase query)?"; then
          read_only_db_user "$P_NAME" "$P_REF"
        fi
        ;;
    esac
  done
  pause

  # ── Project: instructions for agents working in it ──
  stage "Project $P_NAME — tell its agents" 1
  if (( ${#P_SERVICES[@]} == 0 )); then
    say "No services, so agents in this project need no broker instructions."
  else
    # shellcheck disable=SC2068 # one argument per service
    block=$("$SKILL_DIR/scripts/snippet.sh" "$P_NAME" ${P_SERVICES[@]})
    printf '%s' "$block" | pbcopy
    say "Agents working in this folder need to know which commands to use. This block is in your clipboard:"
    printf '%s\n' "$block" | sed -n '1,8p' | sed 's/^/    /'
    note "    ... ($(printf '%s\n' "$block" | wc -l | tr -d ' ') lines)"
    target=""
    for candidate in AGENTS.md AGENTS.MD CLAUDE.md; do [[ -f "$P_PATH/$candidate" ]] && { target="$P_PATH/$candidate"; break; }; done
    target=${target:-$P_PATH/AGENTS.md}
    if confirm_yes "Add it to $target? (running again replaces the old block)"; then
      # shellcheck disable=SC2068
      "$SKILL_DIR/scripts/snippet.sh" "$P_NAME" ${P_SERVICES[@]} --write "$target" && DONE+=("$P_NAME: agent instructions in $(basename "$target")")
    else
      SKIPPED+=("$P_NAME: paste the agent instructions (scripts/snippet.sh $P_NAME) into its AGENTS.md or CLAUDE.md")
    fi
  fi
  pause
done

stage "Check" 1
agent-broker projects || warn "agent-broker projects failed"
say "Each project shows its key names. Values never show here or anywhere else."
pause

if [[ "$MODE" == setup ]]; then
  stage "Log out the global logins" 1
  say "After this, a Netlify, Supabase or Apify command run without the broker fails instead of using"
  say "whatever account happens to be logged in. gh (GitHub) stays logged in."
  if confirm_yes "Log out of Netlify, Supabase and Apify now?"; then
    if command -v netlify >/dev/null; then netlify logout || SKIPPED+=("netlify logout"); fi
    if command -v supabase >/dev/null; then supabase logout --yes || SKIPPED+=("supabase logout"); fi
    if command -v apify >/dev/null; then apify logout || SKIPPED+=("apify logout"); fi
    DONE+=("global logins removed (Netlify, Supabase, Apify)")
  else
    SKIPPED+=("log out: netlify logout; supabase logout; apify logout")
  fi
fi

finish
for d in ${DONE[@]+"${DONE[@]}"}; do note "✓ $d"; done
printf '\n  Tell your agent "done": it tests the broker with your accounts. Add more projects later with:\n'
printf '  %s/scripts/wizard.sh add-project\n\n' "$SKILL_DIR"
