#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Agent broker wizard: account stacks and projects, with tokens that agents cannot read.
# Run it in your own Terminal (the Terminal app, not an agent). Each save asks for Touch ID / your Mac password once.
# Tokens are typed hidden and go straight into the broker. Guide: ../SKILL.md
#   wizard.sh            menu (first run: setup first)

ENV_FILE=/dev/null # nothing is remembered in files: tokens live only in the broker and your vault
SKILL_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
BROKER_SRC="$SKILL_DIR/broker"
VAULT_DIR="$HOME/Secrets"
GUARD_DIR=/opt/agent-broker/guard
DONE=()
# filled by ask / ask_default / pick (printf -v)
P_PATH="" P_NAME="" P_REF="" STACK="" STACK_NEW="" choice="" site="" dir="" move="" conn="" svc=""
LOOKUP="{}" PROJECT_LINES="" ARGS=()
# Tokens typed in this run (read indirectly as ${!var}); cleared as soon as they are saved.
# shellcheck disable=SC2034
clear_tokens() { T_NETLIFY="" T_SUPABASE="" T_APIFY="" T_VERCEL=""; }
clear_tokens

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2; exit 1; }
ok() { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; DONE+=("$1"); }

# begin "Title" <stages> <minutes> — start one menu action with its own progress counter.
begin() {
  TOTAL_STAGES=$2 TOTAL_MINUTES=$3 _STAGE_INDEX=0 _MINUTES_ELAPSED=0
  _clear
  printf '\n%s%s  %s%s  %s(%s steps · about %s min)%s\n' "$BOLD" "$BLUE" "$1" "$RESET" "$DIM" "$2" "$3" "$RESET"
}

# ask_default VAR "Prompt" default — visible input; Enter keeps the default.
ask_default() {
  local input
  if [[ -n "$3" ]]; then printf '  %s%s%s %s[%s]%s ' "$BOLD" "$2" "$RESET" "$DIM" "$3" "$RESET"; else printf '  %s%s%s ' "$BOLD" "$2" "$RESET"; fi
  read -r input || true
  printf -v "$1" '%s' "${input:-$3}"
}

# confirm_yes "question" — Y/n gate; yes unless the answer starts with n.
confirm_yes() {
  local reply=""
  printf '  %s? %s [Y/n] ' "$YELLOW" "$1"
  read -r reply || true
  [[ ! "$reply" =~ ^[Nn] ]]
}

# js EXPR — run a JS expression on the JSON from stdin (as `d`); prints the result (strings as-is).
js() {
  node -e 'let s = ""; process.stdin.on("data", (c) => (s += c)).on("end", () => {
    const d = JSON.parse(s || "null"); const r = new Function("d", `return (${process.argv[1]})`)(d);
    if (r !== undefined && r !== null) process.stdout.write(typeof r === "string" ? r : JSON.stringify(r)); })' "$1"
}

# pick VAR "Title" "lines" [extra] — numbered menu of "label<TAB>value" lines; VAR = chosen value.
# extra "new<TAB>Label" adds a lettered option whose value is returned as-is.
pick() {
  local var=$1 title=$2 lines=$3 extra=${4:-} n=0 i input
  local values=()
  printf '\n  %s%s%s\n' "$BOLD" "$title" "$RESET"
  while IFS=$'\t' read -r label value; do
    [[ -z "$label" ]] && continue
    n=$((n + 1)); values+=("$value")
    printf '   %s%2d%s  %s\n' "$BLUE" "$n" "$RESET" "$label"
  done <<<"$lines"
  [[ -n "$extra" ]] && printf '   %s n%s  %s\n' "$BLUE" "$RESET" "${extra#*$'\t'}"
  while :; do
    printf '  %sNumber:%s ' "$BOLD" "$RESET"
    read -r input || true
    if [[ -n "$extra" && "$input" == n ]]; then printf -v "$var" '%s' "${extra%%$'\t'*}"; return; fi
    if [[ "$input" =~ ^[0-9]+$ ]] && (( input >= 1 && input <= n )); then
      i=$((input - 1)); printf -v "$var" '%s' "${values[$i]}"; return
    fi
    warn "Type a number from the list."
  done
}

# admin ARGS... (stdin passed through) — agent-broker-admin with one retry (wrong password, Touch ID cancelled).
admin() {
  local input
  input=$(cat)
  printf '%s' "$input" | agent-broker-admin "$@" && return 0
  warn "That did not work (see the message above)."
  if confirm "Try again?" </dev/tty; then printf '%s' "$input" | agent-broker-admin "$@" && return 0; fi
  return 1
}

# real_cli NAME — the real netlify / supabase / apify / vercel, not the agent-broker guard.
real_cli() {
  local d
  local IFS=:
  for d in $PATH; do
    [[ "$d" == "$GUARD_DIR" || -z "$d" ]] && continue
    [[ -x "$d/$1" ]] && { printf '%s' "$d/$1"; return 0; }
  done
  return 1
}

token_var() { case "$1" in netlify) echo T_NETLIFY ;; supabase) echo T_SUPABASE ;; apify) echo T_APIFY ;; vercel) echo T_VERCEL ;; esac; }
token_key() { case "$1" in netlify) echo NETLIFY_AUTH_TOKEN ;; supabase) echo SUPABASE_ACCESS_TOKEN ;; apify) echo APIFY_TOKEN ;; vercel) echo VERCEL_TOKEN ;; esac; }
service_title() { case "$1" in netlify) echo Netlify ;; supabase) echo Supabase ;; apify) echo Apify ;; vercel) echo Vercel ;; esac; }

# ask_token SERVICE — open the token page, read the token hidden into T_<SERVICE>.
ask_token() {
  local s=$1 url how
  case "$s" in
    netlify) url="https://app.netlify.com/user/applications#personal-access-tokens"; how="New access token. Name: agent-broker. Expiry: your choice." ;;
    supabase) url="https://supabase.com/dashboard/account/tokens"; how="Generate new token. Name: agent-broker." ;;
    apify) url="https://console.apify.com/settings/integrations"; how="Copy the API token (or create a new one)." ;;
    vercel) url="https://vercel.com/account/settings/tokens"; how="Create token. Scope: the team that owns the projects." ;;
  esac
  printf '\n  %s%s token%s\n' "$BOLD" "$(service_title "$s")" "$RESET"
  step "Log in to the RIGHT $(service_title "$s") account first."
  open_url "$url"
  step "$how"
  step "Save it in KeePassXC too."
  ask_secret "$(token_var "$s")" "Paste the token (hidden):"
}

# lookup_tokens — LOOKUP = accounts, sites and databases for the T_* tokens typed in this run.
lookup_tokens() {
  local lines="" s v
  for s in netlify supabase apify vercel; do
    v=$(token_var "$s"); [[ -n "${!v}" ]] && lines+="$(token_key "$s")=${!v}"$'\n'
  done
  [[ -z "$lines" ]] && return 0
  say "Checking the token(s)..."
  local found
  found=$(printf '%s' "$lines" | node "$SKILL_DIR/scripts/lookup.mjs") || die "Could not check the tokens (network?)."
  LOOKUP=$(printf '%s\n%s' "$LOOKUP" "$found" | node -e 'let s = ""; process.stdin.on("data", (c) => (s += c)).on("end", () => {
    const [a, b] = s.split("\n"); console.log(JSON.stringify({ ...JSON.parse(a), ...JSON.parse(b) })) })')
}

# show_accounts — one line per service: who the token belongs to. Fails on a bad token.
show_accounts() {
  local lines
  lines=$(printf '%s' "$LOOKUP" | js 'Object.entries(d).map(([s, r]) => r.error ? `ERROR\t${s}: ${r.error}` : `${s}\t${[r.account?.name, r.account?.email && "<" + r.account.email + ">"].filter(Boolean).join(" ")}${r.account?.teams?.length ? "  teams: " + r.account.teams.join(", ") : r.account?.orgs?.length ? "  orgs: " + r.account.orgs.join(", ") : ""}`).join("\n")')
  while IFS=$'\t' read -r s who; do
    [[ -z "$s" ]] && continue
    if [[ "$s" == ERROR ]]; then warn "$who"; return 1; fi
    printf '   %s%-9s%s %s\n' "$BOLD" "$s" "$RESET" "$who"
  done <<<"$lines"
}

stack_lines() { agent-broker stacks | js 'd.map((s) => `${s.stack}   ${Object.entries(s.accounts).map(([k, a]) => `${k}: ${a.email ?? a.name ?? (a.orgs ?? []).join(", ")}`).join(" · ") || "no tokens yet"}   (projects: ${s.projects.join(", ") || "none"})\t${s.stack}`).join("\n")'; }
project_lines() { agent-broker projects | js 'd.map((p) => `${p.project}   ${p.stack ? "stack " + p.stack : "no stack"}   ${p.folders.join(", ")}\t${p.project}`).join("\n")'; }

# choose_stack — STACK (+ STACK_NEW=1 and typed tokens for a new stack). Fills LOOKUP for its tokens.
choose_stack() {
  STACK="" STACK_NEW="" LOOKUP="{}"
  clear_tokens
  local stacks
  stacks=$(stack_lines)
  if [[ -n "$stacks" ]]; then
    pick STACK "Which account stack? (a stack = one login per service)" "$stacks" $'new\tNew stack (new logins)'
  else
    say "No stacks yet: let's make the first one."
    STACK=new
  fi
  if [[ "$STACK" == new ]]; then
    STACK_NEW=1
    while :; do
      ask_default STACK "Name the stack after its login (e.g. thedoor, studio):" ""
      [[ "$STACK" =~ ^[a-z0-9][a-z0-9_-]{0,62}$ ]] && break
      warn "Lowercase letters, digits, - and _ only."
    done
    for svc in netlify supabase apify vercel; do
      if confirm "Does this stack have a $(service_title "$svc") login?"; then ask_token "$svc"; fi
    done
    lookup_tokens
    say "These tokens belong to:"
    show_accounts || die "A token did not work. Run the wizard again with a fresh token."
    confirm_yes "Are these the right accounts?" || die "Stopped: nothing was saved."
  else
    say "Reading stack $STACK (Touch ID)..."
    LOOKUP=$(agent-broker-admin lookup "$STACK") || die "Could not read stack $STACK."
    show_accounts || warn "One of the stack's tokens did not work: replace it (menu: Replace a token)."
  fi
}

# stack_value_lines — stack:KEY=VALUE lines for tokens typed in this run.
stack_value_lines() {
  local s v
  for s in netlify supabase apify vercel; do
    v=$(token_var "$s"); [[ -n "${!v}" ]] && printf 'stack:%s=%s\n' "$(token_key "$s")" "${!v}"
  done
  return 0
}

# choose_pins FOLDER — ask which services the project uses and pick its site / database from lists. Adds to ARGS.
choose_pins() {
  local folder=$1 found list ref org pid publish
  for svc in netlify supabase vercel apify; do
    local has_token=""
    [[ -n "$(printf '%s' "$LOOKUP" | js "d.$svc && !d.$svc.error ? 'y' : ''")" ]] && has_token=1
    if [[ -n "$has_token" ]]; then confirm_yes "Does this project use $(service_title "$svc")?" || continue
    else confirm "Does this project use $(service_title "$svc")?" || continue
    fi
    if [[ -z "$has_token" ]]; then
      say "Stack $STACK has no $(service_title "$svc") token yet."
      ask_token "$svc"
      lookup_tokens
      show_accounts || die "The token did not work."
    fi
    case "$svc" in
      netlify)
        found=$(node -e 'try { console.log(JSON.parse(require("fs").readFileSync(process.argv[1], "utf8")).siteId ?? "") } catch {}' "$folder/.netlify/state.json")
        list=$(printf '%s' "$LOOKUP" | js "(d.netlify.sites ?? []).map((s) => \`\${s.name}   \${s.url}\${s.id === '$found' ? '   ← this folder' : ''}\t\${s.id}\`).join('\n')")
        [[ -n "$list" ]] || die "This Netlify account has no sites. Create the site in Netlify first."
        pick site "Which Netlify site?" "$list"
        publish=$(sed -nE 's/^[[:space:]]*publish[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' "$folder/netlify.toml" 2>/dev/null | head -1)
        ask_default dir "Folder with the built files:" "${publish:-dist}"
        ARGS+=(--netlify-site "$site" --netlify-dir "$dir")
        ;;
      supabase)
        list=$(printf '%s' "$LOOKUP" | js "(d.supabase.projects ?? []).map((p) => \`\${p.name}   \${p.ref}   (\${p.org}, \${p.status})\t\${p.ref}\`).join('\n')")
        [[ -n "$list" ]] || die "This Supabase account has no projects."
        pick ref "Which Supabase project?" "$list"
        ARGS+=(--supabase-ref "$ref")
        P_REF=$ref
        ;;
      vercel)
        list=$(printf '%s' "$LOOKUP" | js "(d.vercel.projects ?? []).map((p) => \`\${p.name}   (\${p.scope})\t\${p.org_id} \${p.id}\`).join('\n')")
        [[ -n "$list" ]] || die "This Vercel account has no projects."
        pick pid "Which Vercel project?" "$list"
        org=${pid%% *}
        ARGS+=(--vercel-org "$org" --vercel-project "${pid#* }")
        ;;
      apify)
        ask_default dir "Folder with the actor (.actor/actor.json), inside the project:" "."
        ARGS+=(--apify --apify-dir "$dir")
        ;;
    esac
  done
}

# env_secrets FOLDER — offer to move .env secrets; appends project:KEY=VALUE to PROJECT_LINES; MOVED = "file:keys" list.
MOVED=()
env_secrets() {
  local folder=$1 f suggested k line
  local files=()
  # Collect first: the loop body prompts, so it must read the keyboard, not this list.
  while IFS= read -r f; do files+=("$f"); done < <(find "$folder" -maxdepth 1 -type f -name '.env*' ! -name '*.example' ! -name '*.sample' ! -name '*.template' 2>/dev/null | sort)
  for f in ${files[@]+"${files[@]}"}; do
    printf '\n  %s%s%s\n' "$BOLD" "$f" "$RESET"
    note "Keys: $(grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$f" | tr -d '=' | tr '\n' ' ')"
    suggested=$(awk '/^[A-Za-z_][A-Za-z0-9_]*=/ { i = index($0, "="); k = substr($0, 1, i - 1); v = substr($0, i + 1)
      if (k ~ /(ANON|PUBLISHABLE|PUBLIC)/) next
      if (k ~ /(TOKEN|SECRET|PASSWORD|PASSWD|SERVICE_ROLE|PRIVATE|API_KEY|ACCESS_KEY)/ || v ~ /:\/\/[^\/:@]+:[^@]+@/) printf "%s ", k }' "$f")
    say "Agents can read this file. Move secrets into the broker. Keep public values (URLs, anon keys, ids)."
    ask_default move "Keys to move (space between them; - = none):" "${suggested% }"
    [[ -z "$move" || "$move" == - ]] && continue
    step "Save these in KeePassXC first (they leave this file)."
    if confirm "Show the values here once, to copy them?"; then
      for k in $move; do grep -m1 "^$k=" "$f" | sed 's/^/    /' || true; done
      pause "Press Enter when saved"
      _clear
    fi
    for k in $move; do
      line=$(grep -m1 "^$k=" "$f" || true)
      [[ -n "$line" ]] || { warn "$k is not in $f: skipped"; continue; }
      PROJECT_LINES+="project:$line"$'\n'
    done
    MOVED+=("$f:$move")
  done
}

# remove_moved — delete the moved keys from their .env files (after the broker saved them).
remove_moved() {
  local entry f keys pattern kept
  for entry in ${MOVED[@]+"${MOVED[@]}"}; do
    f=${entry%%:*} keys=${entry#*:}
    # shellcheck disable=SC2086 # one key per word
    pattern=$(printf '^%s=|' $keys)
    kept=$(grep -vE "${pattern%|}" "$f" || true)
    printf '%s\n' "$kept" >"$f"
    ok "removed $keys from $(basename "$f")"
  done
  MOVED=()
}

# read_only_user REF — a read-only database user for `agent-broker supabase query`; adds project:SUPABASE_READ_URL.
read_only_user() {
  local ref=$1 pw url
  pw=$(openssl rand -hex 24)
  pbcopy <<SQL
-- agent_reader: read-only database user for agents (agent-broker supabase query).
do \$\$ begin
  if not exists (select 1 from pg_roles where rolname = 'agent_reader') then create role agent_reader login; end if;
end \$\$;
alter role agent_reader with login password '$pw' bypassrls noinherit;
alter role agent_reader set default_transaction_read_only = on;
alter role agent_reader set statement_timeout = '120s';
grant usage on schema public to agent_reader;
grant select on all tables in schema public to agent_reader;
alter default privileges in schema public grant select on tables to agent_reader;
SQL
  open_url "https://supabase.com/dashboard/project/$ref/sql/new"
  step "The SQL is in your clipboard. Paste it. Click Run."
  pause "Press Enter when it ran with no error"
  printf '' | pbcopy
  open_url "https://supabase.com/dashboard/project/$ref"
  step "Click Connect (top). Pick Session pooler. Copy the connection string."
  ask conn "Paste it:"
  url=${conn/postgres.$ref:/agent_reader.$ref:}
  url=${url/\[YOUR-PASSWORD\]/$pw}
  if [[ "$url" != *"agent_reader.$ref:$pw@"* ]]; then
    warn "That is not the Session pooler string for $ref. Skipped: agents cannot run SQL until you add it."
    return
  fi
  PROJECT_LINES+="project:SUPABASE_READ_URL=$url"$'\n'
}

# tell_agents PROJECT FOLDER — write the AGENTS.md block, copy it, show whoami.
tell_agents() {
  local p=$1 folder=$2 target=""
  "$SKILL_DIR/scripts/snippet.sh" "$p" | pbcopy
  for f in AGENTS.md AGENTS.MD CLAUDE.md; do [[ -f "$folder/$f" ]] && { target="$folder/$f"; break; }; done
  target=${target:-$folder/AGENTS.md}
  if confirm_yes "Put the agent instructions in $(basename "$target")? (also in your clipboard)"; then
    "$SKILL_DIR/scripts/snippet.sh" "$p" --write "$target" >/dev/null && ok "$p: instructions in $(basename "$target")"
  fi
  say "What an agent in this folder sees:"
  (cd "$folder" && agent-broker whoami) | js '`   project ${d.project} · stack ${d.stack ?? "-"} · ${Object.entries(d.services).map(([s, c]) => `${s} ${c.site_name ?? c.name ?? ""}${c.token ? "" : " (no token!)"}`.trim()).join(" · ") || "no services"}`'
  printf '\n'
}

# ── Actions ──────────────────────────────────────────────────────────────

action_add_project() {
  begin "Add a project" 6 10
  ARGS=() PROJECT_LINES="" P_REF="" MOVED=()

  stage "Folder" 1
  ask_default P_PATH "Project folder:" "$( [[ "$PWD" != "$HOME" ]] && printf '%s' "$PWD")"
  P_PATH=${P_PATH/#\~/$HOME}; P_PATH=${P_PATH%/}
  [[ -d "$P_PATH" ]] || die "No such folder: $P_PATH"
  P_PATH=$(cd "$P_PATH" && pwd -P)
  local default_name
  default_name=$(basename "$P_PATH" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9_\n-' '-')
  while :; do
    ask_default P_NAME "Project name:" "$default_name"
    [[ "$P_NAME" =~ ^[a-z0-9][a-z0-9_-]{0,62}$ ]] || { warn "Lowercase letters, digits, - and _ only."; continue; }
    [[ -z "$(agent-broker projects | js "d.find((p) => p.project === '$P_NAME') ? 'y' : ''")" ]] && break
    warn "$P_NAME already exists. Pick another name (or use menu: Add a folder)."
  done

  stage "Account stack" 3
  choose_stack

  stage "What it uses" 2
  choose_pins "$P_PATH"

  stage ".env secrets" 2
  env_secrets "$P_PATH"
  if [[ -n "$P_REF" ]] && confirm_yes "Make a read-only database user, so agents can read the database?"; then read_only_user "$P_REF"; fi

  stage "Save (Touch ID)" 1
  ARGS=(apply --project "$P_NAME" --new-project --path "$P_PATH" --stack "$STACK" ${STACK_NEW:+--new-stack} ${ARGS[@]+"${ARGS[@]}"})
  if { stack_value_lines; printf '%s' "$PROJECT_LINES"; } | admin "${ARGS[@]}"; then
    ok "project $P_NAME saved (stack $STACK)"
    remove_moved
  else
    die "Nothing was saved."
  fi
  clear_tokens
  PROJECT_LINES=""

  stage "Tell its agents" 1
  tell_agents "$P_NAME" "$P_PATH"
  pause
}

action_replace_token() {
  begin "Replace a token" 3 3
  local stacks
  stacks=$(stack_lines)
  [[ -n "$stacks" ]] || { warn "No stacks yet."; pause; return; }
  stage "Which token" 1
  pick STACK "Which stack?" "$stacks"
  pick svc "Which service?" $'Netlify\tnetlify\nSupabase\tsupabase\nApify\tapify\nVercel\tvercel'
  clear_tokens
  LOOKUP="{}"
  stage "New token" 1
  ask_token "$svc"
  lookup_tokens
  say "The new token belongs to:"
  show_accounts || die "The token did not work."
  agent-broker stacks | js "const a = d.find((s) => s.stack === '$STACK')?.accounts?.$svc; a ? '   before: ' + [a.name, a.email].filter(Boolean).join(' ') : ''"
  printf '\n'
  confirm_yes "Same account as before? Save it for every project on stack $STACK?" || die "Stopped: nothing was saved."
  stage "Save (Touch ID)" 1
  stack_value_lines | admin apply --stack "$STACK" && ok "stack $STACK: new $(service_title "$svc") token"
  clear_tokens
  step "Now delete the old token on the $(service_title "$svc") website, and update KeePassXC."
  pause
}

action_move_project() {
  begin "Move a project to another stack" 4 6
  ARGS=() PROJECT_LINES="" P_REF=""
  local projects
  projects=$(project_lines)
  [[ -n "$projects" ]] || { warn "No projects yet."; pause; return; }
  stage "Project" 1
  pick P_NAME "Which project?" "$projects"
  P_PATH=$(agent-broker projects | js "d.find((p) => p.project === '$P_NAME').folders[0]")
  stage "New stack" 2
  choose_stack
  stage "Its site and database in that account" 2
  choose_pins "$P_PATH"
  stage "Save (Touch ID)" 1
  ARGS=(apply --project "$P_NAME" --stack "$STACK" ${STACK_NEW:+--new-stack} ${ARGS[@]+"${ARGS[@]}"})
  stack_value_lines | admin "${ARGS[@]}" && ok "project $P_NAME now on stack $STACK"
  clear_tokens
  tell_agents "$P_NAME" "$P_PATH"
  pause
}

action_add_folder() {
  begin "Add a folder to a project" 2 2
  local projects
  projects=$(project_lines)
  [[ -n "$projects" ]] || { warn "No projects yet."; pause; return; }
  stage "Folder" 1
  note "For a second copy of the same repo (a clone or git worktree). Worktrees of a registered repo work already."
  pick P_NAME "Which project?" "$projects"
  ask P_PATH "Extra folder:"
  P_PATH=${P_PATH/#\~/$HOME}
  [[ -d "$P_PATH" ]] || die "No such folder: $P_PATH"
  stage "Save (Touch ID)" 1
  printf '' | admin apply --project "$P_NAME" --add-path "$P_PATH" && ok "$P_NAME: added $P_PATH"
  pause
}

action_agents_text() {
  begin "AGENTS.md text" 1 1
  local projects
  projects=$(project_lines)
  [[ -n "$projects" ]] || { warn "No projects yet."; pause; return; }
  stage "Project" 1
  pick P_NAME "Which project?" "$projects"
  "$SKILL_DIR/scripts/snippet.sh" "$P_NAME" | sed 's/^/    /'
  tell_agents "$P_NAME" "$(agent-broker projects | js "d.find((p) => p.project === '$P_NAME').folders[0]")"
  pause
}

action_setup() {
  begin "Set up / update the broker" 4 12
  stage "Your vault (KeePassXC)" 4
  say "KeePassXC = your own copy of every token. Agents never use it."
  if [[ ! -d /Applications/KeePassXC.app ]]; then
    if confirm_yes "Install KeePassXC now (Homebrew)?"; then brew install --cask keepassxc; fi
  fi
  mkdir -p "$VAULT_DIR" && chmod 700 "$VAULT_DIR"
  open -a KeePassXC 2>/dev/null || true
  if compgen -G "$VAULT_DIR/*.kdbx" >/dev/null; then
    step "Unlock your vault in KeePassXC."
  else
    step "KeePassXC: Create new database. Strong master password."
    step "Save it as $VAULT_DIR/tokens.kdbx"
  fi
  pause "Press Enter when the vault is open"

  stage "Install the broker (Touch ID)" 5
  say "Installs the broker, its own CLIs (~300 MB) and the CLI guard. Safe to repeat."
  (cd "$BROKER_SRC" && node --test test/*.test.mjs >/dev/null 2>&1) || die "The broker's tests fail: ask your agent to fix them."
  confirm_yes "Install / update now?" || return
  (cd "$BROKER_SRC" && sudo ./install.sh) || die "The install failed (see above)."
  ok "broker installed"

  stage "Projects from before stacks" 2
  local legacy p
  legacy=$(agent-broker projects | js 'd.filter((p) => !p.stack && p.keys.some((k) => ["NETLIFY_AUTH_TOKEN", "SUPABASE_ACCESS_TOKEN", "APIFY_TOKEN", "VERCEL_TOKEN"].includes(k))).map((p) => p.project).join("\n")')
  if [[ -z "$legacy" ]]; then say "None. Nothing to move."; fi
  local p projects=()
  while IFS= read -r p; do [[ -n "$p" ]] && projects+=("$p"); done <<<"$legacy"
  for p in ${projects[@]+"${projects[@]}"}; do
    say "Project $p holds its own account token. Move it into a stack (so other projects can share it)."
    ask_default STACK "Stack name (name it after the login):" "$p"
    printf '' | admin apply --stack "$STACK" --new-stack --stack-from-project "$p" --project "$p" && ok "$p: token moved to stack $STACK"
    tell_agents "$p" "$(agent-broker projects | js "d.find((x) => x.project === '$p').folders[0]")"
  done

  stage "Log out the global logins" 1
  say "Then no command can fall back to whatever account is logged in. gh (GitHub) stays."
  if confirm_yes "Log out of Netlify, Supabase and Apify?"; then
    local bin
    if bin=$(real_cli netlify); then "$bin" logout >/dev/null 2>&1 || true; fi
    if bin=$(real_cli supabase); then "$bin" logout --yes >/dev/null 2>&1 || true; fi
    if bin=$(real_cli apify); then "$bin" logout >/dev/null 2>&1 || true; fi
    ok "logged out of Netlify, Supabase, Apify"
  fi
  note "Open a new Terminal tab: the CLI guard starts in new shells."
  pause
}

# ── Menu ─────────────────────────────────────────────────────────────────
[[ -t 0 && -t 1 ]] || die "Run this in your own Terminal app, not through an agent."
[[ "$(uname)" == Darwin ]] || die "This wizard is for macOS."
command -v node >/dev/null || die "Node is missing. Install it first."

if ! command -v agent-broker >/dev/null || ! agent-broker stacks >/dev/null 2>&1; then
  command -v brew >/dev/null || die "Homebrew is missing (needed for KeePassXC)."
  action_setup
fi

while :; do
  _clear
  printf '\n%s%s  Agent broker%s  %s(tokens agents cannot read)%s\n\n' "$BOLD" "$BLUE" "$RESET" "$DIM" "$RESET"
  printf '   %s1%s  Add a project            %s(new folder; new or existing stack)%s\n' "$BLUE" "$RESET" "$DIM" "$RESET"
  printf '   %s2%s  Replace a token          %s(one place, every project on the stack)%s\n' "$BLUE" "$RESET" "$DIM" "$RESET"
  printf '   %s3%s  Move a project           %s(to another stack)%s\n' "$BLUE" "$RESET" "$DIM" "$RESET"
  printf '   %s4%s  Add a folder             %s(second copy of a project)%s\n' "$BLUE" "$RESET" "$DIM" "$RESET"
  printf '   %s5%s  AGENTS.md text           %s(for a project)%s\n' "$BLUE" "$RESET" "$DIM" "$RESET"
  printf '   %s6%s  Set up / update          %s(vault, install, log out)%s\n' "$BLUE" "$RESET" "$DIM" "$RESET"
  printf '   %s0%s  Done\n\n' "$BLUE" "$RESET"
  printf '  %sNumber:%s ' "$BOLD" "$RESET"
  read -r choice || choice=0
  case "$choice" in
    1) action_add_project ;;
    2) action_replace_token ;;
    3) action_move_project ;;
    4) action_add_folder ;;
    5) action_agents_text ;;
    6) action_setup ;;
    0 | q | "") break ;;
  esac
done

finish
for d in ${DONE[@]+"${DONE[@]}"}; do note "✓ $d"; done
printf '\n'
